import{i as l,a as q,S as R}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const M="48661000-87492d5612d6e41eb1a42ef3d",A="https://pixabay.com/api/";async function g(t){if(!t||typeof t!="string"||t.trim()==="")return l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"}),null;try{const e=await q.get(A,{params:{key:M,q:encodeURIComponent(t),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});if(console.log("API Response:",e.data),e.status!==200)throw new Error(`API error: ${e.status}`);return e.data}catch(e){return console.error("Error fetching images:",e),l.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"}),null}}const i=document.querySelector(".gallery"),F=new R(".gallery a",{captionsData:"alt",captionDelay:250}),a=document.querySelector(".load-more"),v=document.getElementById("loading-overlay"),n=document.createElement("p");n.classList.add("end-message");n.textContent="We're sorry, but you've reached the end of search results.";n.style.display="none";i.after(n);let d="";const b=40;let p=0,y=new Set;a.style.display="none";n.style.display="none";async function f(t,e=!1){if(!Array.isArray(t)||t.length===0){w();return}const s=t.filter(r=>y.has(r.id)?!1:(y.add(r.id),!0));e||(i.innerHTML="",y.clear());const u=s.map(({webformatURL:r,largeImageURL:o,tags:c,likes:I,views:$,comments:P,downloads:S})=>`
    <div class="gallery-item">
      <a href="${o}">
        <img src="${r}" alt="${c}" loading="lazy" />
      </a>
      <div class="image-info">
        <div class="item"><span class="label">Likes</span><span class="count">${I}</span></div>
        <div class="item"><span class="label">Views</span><span class="count">${$}</span></div>
        <div class="item"><span class="label">Comments</span><span class="count">${P}</span></div>
        <div class="item"><span class="label">Downloads</span><span class="count">${S}</span></div>
      </div>
    </div>`).join("");i.insertAdjacentHTML("beforeend",u),F.refresh(),i.children.length>=p?(a.style.display="none",n.style.display="block"):i.children.length>=b&&(a.style.display="block",n.style.display="none")}function w(){i.innerHTML=`
    <p class="error-message">
      Sorry, no images match your search. Please try again!
    </p>
  `,a.style.display="none",n.style.display="none"}const m=document.querySelector(".search-form"),h=document.querySelector('input[name="searchQuery"]');m&&h?m.addEventListener("submit",async t=>{var s;if(t.preventDefault(),d=(s=h.value)==null?void 0:s.trim(),!d){console.error("Invalid search input:",d);return}y.clear(),a.style.display="none",n.style.display="none";const e=await g(d);e&&e.hits.length>0?(p=e.totalHits,await f(e.hits),p>b&&(a.style.display="block")):w()}):console.error("Search form or input not found in DOM");a.addEventListener("click",async()=>{if(i.children.length>=p){a.style.display="none",n.style.display="block";return}O();const t=await g(d);t&&t.hits&&await f(t.hits,!0),x()});function O(){v.style.display="block"}function x(){v.style.display="none"}document.querySelector(".gallery");const D=document.querySelector(".search-form");function L(){document.getElementById("loading-overlay").style.display="flex"}function E(){document.getElementById("loading-overlay").style.display="none"}async function B(){L();try{const t=["nature","technology","art","food","travel"],e=t[Math.floor(Math.random()*t.length)];console.log(`Fetching images for: ${e}`);const s=await g(e);if(!s||!s.hits||s.hits.length===0){l.warning({title:"Info",message:`No images found for query: ${e}. Try another one.`,position:"topRight"});return}console.log(`Fetched ${s.hits.length} images for query: ${e}`),f(s.hits)}catch(t){l.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"}),console.error("Error fetching random images:",t)}finally{E()}}B();D.addEventListener("submit",async t=>{t.preventDefault();const e=t.target.elements.searchQuery.value.trim();if(!e){l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}L();try{const s=await g(e);if(!s||!s.hits||s.hits.length===0){l.info({title:"Info",message:"No images found for your query.",position:"topRight"});return}console.log(`Fetched ${s.hits.length} images for query: ${e}`),f(s.hits)}catch(s){l.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"}),console.error("Error fetching search images:",s)}finally{E()}});
//# sourceMappingURL=index.js.map
